using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.9.2.41")]
[assembly: AssemblyTitleAttribute("NAnt-Gui.Core")]
[assembly: AssemblyDescriptionAttribute("Executes and edits NAnt build scripts")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2005, Colin Svingen")]
[assembly: AssemblyProductAttribute("NAnt-Gui")]

