using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.9.2.41")]
[assembly: AssemblyTitleAttribute("NAnt-Gui.Core")]
[assembly: AssemblyDescriptionAttribute("Executes and edits NAnt build scripts")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2005, Colin Svingen")]
[assembly: AssemblyProductAttribute("NAnt-Gui")]

