//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAntGui.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAntGui.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading file &apos;{0}&apos;.{1}The error was: {2}.
        /// </summary>
        internal static string CouldNotLoadError {
            get {
                return ResourceManager.GetString("CouldNotLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading File.
        /// </summary>
        internal static string CouldNotLoadTitle {
            get {
                return ResourceManager.GetString("CouldNotLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving file &apos;{0}&apos;.{1}The error was: {2}.
        /// </summary>
        internal static string CouldNotSaveError {
            get {
                return ResourceManager.GetString("CouldNotSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving File.
        /// </summary>
        internal static string CouldNotSaveTitle {
            get {
                return ResourceManager.GetString("CouldNotSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes to &quot;{0}&quot;. Save?.
        /// </summary>
        internal static string DocumentNotSaved {
            get {
                return ResourceManager.GetString("DocumentNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string DocumentNotSavedTitle {
            get {
                return ResourceManager.GetString("DocumentNotSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{1}This document has changed outside of NAnt-Gui.{1}Would you like to reload it?.
        /// </summary>
        internal static string FileChanged {
            get {
                return ResourceManager.GetString("FileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Changed.
        /// </summary>
        internal static string FileChangedTitle {
            get {
                return ResourceManager.GetString("FileChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; doesn&apos;t exist anymore.{1}Keep this file in the editor?.
        /// </summary>
        internal static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Deleted.
        /// </summary>
        internal static string FileDeletedTitle {
            get {
                return ResourceManager.GetString("FileDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; was not found..
        /// </summary>
        internal static string FileNotFoundError {
            get {
                return ResourceManager.GetString("FileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build File Not Found.
        /// </summary>
        internal static string FileNotFoundTitle {
            get {
                return ResourceManager.GetString("FileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help not found. It may not have been installed..
        /// </summary>
        internal static string HelpNotFoundError {
            get {
                return ResourceManager.GetString("HelpNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Not Found.
        /// </summary>
        internal static string HelpNotFoundTitle {
            get {
                return ResourceManager.GetString("HelpNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project template missing.  Please re-install the application..
        /// </summary>
        internal static string ProjectTemplateMissingError {
            get {
                return ResourceManager.GetString("ProjectTemplateMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reload the current file and lose the changes you have made?.
        /// </summary>
        internal static string ReloadUnsaved {
            get {
                return ResourceManager.GetString("ReloadUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string ReloadUnsavedTitle {
            get {
                return ResourceManager.GetString("ReloadUnsavedTitle", resourceCulture);
            }
        }
    }
}
